[service]
port = 8080

[internalstorage]
path = "example_storage.toml"

[converter]
endpoint = "https://api.coinpaprika.com/v1/price-converter"
#"https://api.coinpaprika.com/v1/price-converter?base_currency_id=btc-bitcoin&quote_currency_id=uah-ukrainian-hryvnia&amount=1"